AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for Checkpoint 10

Parameters:
  MyName:
    Type: String
    Default: Yasmine

Resources:
  SGCheckpoint:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-4c243025
      GroupDescription: Security group for EC2 instance.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
       ImageId: ami-07eda9385feb1e969
       InstanceType: t2.nano
       SecurityGroupIds:
          - !Ref SGCheckpoint
       Tags:
         -
          Key: "Owner"
          Value: "Yasmine"

Outputs:
  MyEC2InstancePublicDNSName:
    Value: !GetAtt MyEC2Instance.PublicDnsName
    Description: EC2 instance public DNS name